import type { WebSocket } from "ws";
import { DeepgramClient } from "@deepgram/sdk";
import type { Config } from "../config";
import { log } from "../util/logger";

const logger = log("voice:tts");
const SAMPLE_RATE = 24000;

type Outgoing = { type: "start" | "done" | "cancelled" | "error"; id: string; message?: string };

function sendJson(ws: WebSocket, msg: Outgoing): void {
  if (ws.readyState === ws.OPEN) ws.send(JSON.stringify(msg));
}

function withTimeout<T>(p: Promise<T>, ms: number, label: string): Promise<T> {
  return new Promise((resolve, reject) => {
    const t = setTimeout(() => reject(new Error(`${label} timed out`)), ms);
    p.then(
      (v) => {
        clearTimeout(t);
        resolve(v);
      },
      (e) => {
        clearTimeout(t);
        reject(e);
      },
    );
  });
}

type SpeakSocket = Awaited<ReturnType<DeepgramClient["speak"]["v2"]["connect"]>>;

/**
 * One TTS session per browser connection. Text in → 24kHz linear16 PCM frames out,
 * streamed as they are generated by Deepgram Flux TTS (Speak v2 WebSocket).
 * Only one utterance is ever in flight; a new "speak" or a "cancel" interrupts the old one.
 */
export function attachTtsSession(client: WebSocket, cfg: Config): void {
  const dg = cfg.deepgramApiKey ? new DeepgramClient({ apiKey: cfg.deepgramApiKey }) : null;
  let upstream: SpeakSocket | null = null;
  let connecting: Promise<SpeakSocket | null> | null = null;
  let current: { id: string } | null = null;
  let chain: Promise<void> = Promise.resolve();
  let closed = false;

  const audioChunk = (blob: Blob) => {
    const forId = current?.id;
    chain = chain
      .then(async () => {
        if (!forId || current?.id !== forId || client.readyState !== client.OPEN) return;
        const buf = Buffer.from(await blob.arrayBuffer());
        if (buf.length) client.send(buf, { binary: true });
      })
      .catch((e) => logger.warn("audio forward failed", { error: String(e) }));
  };

  async function ensureUpstream(): Promise<SpeakSocket | null> {
    if (!dg) return null;
    if (upstream && upstream.readyState === 1) return upstream;
    if (connecting) return connecting;
    connecting = (async () => {
      try {
        const conn = await dg.speak.v2.connect({
          model: cfg.ttsModel,
          encoding: "linear16",
          sample_rate: String(SAMPLE_RATE),
          speed: cfg.ttsSpeed,
          expressivity: cfg.ttsExpressivity,
          reconnectAttempts: 0,
        });
        conn.on("message", (m) => {
          if (typeof m === "string") return;
          if (m instanceof Blob) {
            audioChunk(m);
            return;
          }
          switch (m.type) {
            case "Flushed":
              // Acknowledges the flush; audio frames follow, and SpeechMetadata marks the end.
              break;
            case "SpeechMetadata":
              if (current) {
                const id = current.id;
                // Queue behind the audio forwarding chain so "done" arrives after the last frame.
                chain = chain.then(() => {
                  if (current?.id === id) {
                    sendJson(client, { type: "done", id });
                    current = null;
                  }
                });
              }
              break;
            case "SpeechInterrupted":
              break;
            case "Error":
              logger.warn("flux tts error", { code: m.code, description: m.description });
              if (current) {
                sendJson(client, { type: "error", id: current.id, message: m.description });
                current = null;
              }
              break;
            case "Warning":
              logger.warn("flux tts warning", { code: m.code, description: m.description });
              break;
            default:
              break;
          }
        });
        conn.on("error", (e) => logger.warn("flux tts socket error", { error: e.message }));
        conn.on("close", () => {
          if (upstream === conn) upstream = null;
          if (current && !closed) {
            sendJson(client, { type: "error", id: current.id, message: "voice connection closed" });
            current = null;
          }
        });
        conn.connect();
        await withTimeout(conn.waitForOpen(), 6000, "deepgram tts connect");
        upstream = conn;
        logger.info("tts upstream open", { model: cfg.ttsModel, speed: cfg.ttsSpeed, expressivity: cfg.ttsExpressivity });
        return conn;
      } catch (e) {
        logger.error("tts upstream failed", { error: e instanceof Error ? e.message : String(e) });
        return null;
      } finally {
        connecting = null;
      }
    })();
    return connecting;
  }

  /** Non-streaming fallback (REST) when the WebSocket route is unavailable. */
  async function speakViaRest(id: string, text: string): Promise<void> {
    if (!dg) throw new Error("Deepgram is not configured on the server (DEEPGRAM_API_KEY missing).");
    const res = await dg.speak.v2.audio.generate({
      model: cfg.ttsModel,
      text,
      encoding: "linear16",
      sample_rate: SAMPLE_RATE,
      container: "none",
      speed: cfg.ttsSpeed,
      expressivity: cfg.ttsExpressivity,
    });
    const bytes = Buffer.from(await res.arrayBuffer());
    if (current?.id !== id) return;
    sendJson(client, { type: "start", id });
    const chunk = SAMPLE_RATE * 2 * 0.25; // 250ms chunks
    for (let off = 0; off < bytes.length; off += chunk) {
      if (current?.id !== id || client.readyState !== client.OPEN) return;
      client.send(bytes.subarray(off, Math.min(bytes.length, off + chunk)), { binary: true });
    }
    if (current?.id === id) {
      sendJson(client, { type: "done", id });
      current = null;
    }
  }

  client.on("message", (data, isBinary) => {
    if (isBinary) return;
    let msg: { type: string; id?: string; text?: string };
    try {
      msg = JSON.parse(data.toString());
    } catch {
      return;
    }
    if (msg.type === "speak" && msg.id && typeof msg.text === "string") {
      void (async () => {
        const id = msg.id!;
        const text = msg.text!.trim();
        if (current) {
          try {
            upstream?.sendInterrupt({ type: "Interrupt" });
          } catch {
            /* ignore */
          }
          sendJson(client, { type: "cancelled", id: current.id });
        }
        current = { id };
        if (!text) {
          sendJson(client, { type: "done", id });
          current = null;
          return;
        }
        const conn = await ensureUpstream();
        if (current?.id !== id) return;
        if (conn) {
          try {
            sendJson(client, { type: "start", id });
            conn.sendSpeak({ type: "Speak", text });
            conn.sendFlush({ type: "Flush" });
            logger.info("speak", { id, chars: text.length });
            return;
          } catch (e) {
            logger.warn("streaming speak failed; trying REST", { error: String(e) });
          }
        }
        try {
          await speakViaRest(id, text);
          logger.info("speak (rest)", { id, chars: text.length });
        } catch (e) {
          if (current?.id === id) {
            sendJson(client, { type: "error", id, message: e instanceof Error ? e.message : String(e) });
            current = null;
          }
        }
      })();
    } else if (msg.type === "cancel") {
      if (current && (!msg.id || msg.id === current.id)) {
        try {
          upstream?.sendInterrupt({ type: "Interrupt" });
        } catch {
          /* ignore */
        }
        sendJson(client, { type: "cancelled", id: current.id });
        current = null;
      }
    }
  });

  client.on("close", () => {
    closed = true;
    try {
      upstream?.sendClose({ type: "Close" });
    } catch {
      /* ignore */
    }
    upstream?.close();
    upstream = null;
  });
}
